    version: 2
    updates:
      # Maintain dependencies for GitHub Actions
      - package-ecosystem: github-actions
        directory: "/"
        schedule:
      # Run at 04:00 on day 5 of every month
      cron: "0 3 5 * *"
      timezone: Europe/Berlin

  - package-ecosystem: npm
    directory: "/"
    schedule:
      # Run at 04:00 on day 12 of every month
      cron: "0 3 12 * *"
      timezone: Europe/Berlin
    open-pull-requests-limit: 15
